name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ 'pull_request' != github.event_name || (github.event.pull_request.head.repo.git_url != github.event.pull_request.base.repo.git_url) }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk+fx
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: sbt/setup-sbt@v1

      - name: Install Dependencies
        run: |
          pip install numpy
          pip install scikit-learn
          sudo apt-get -y install aspell

      - name: Build
        # We even install the extensions we can't or won't test just to avoid compile errors with them.
        # -Jeremy B May 2021
        run: sbt -v update compile test:compile "test:runMain org.nlogo.workspace.ExtensionInstaller arduino array bitmap csv gis gogo ls matrix nw palette profiler py resource rnd sound sr table time vid view2.5d"

      - name: Test 2D
        run: sbt -v -Dorg.nlogo.onLocal=false test

      - name: Test 3D
        run: sbt -v -Dorg.nlogo.onLocal=false -Dorg.nlogo.is3d=true test

      - name: Failure Debug Info
        if: ${{ failure() }}
        run: |
          pwd
          sudo apt-get -y install tree
          tree
