name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  LIBERICA_URL: https://download.bell-sw.com/java/17.0.3+7/bellsoft-jdk17.0.3+7-linux-amd64-full.tar.gz

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ 'pull_request' != github.event_name || (github.event.pull_request.head.repo.git_url != github.event.pull_request.base.repo.git_url) }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: liberica@17=tgz+${{ env.LIBERICA_URL }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install numpy
          pip install sklearn
          sudo apt-get -y install aspell

      - name: Build
        # We even install the extensions we can't or won't test just to avoid compile errors with them.
        # -Jeremy B May 2021
        run: sbt -v update compile test:compile "test:runMain org.nlogo.workspace.ExtensionInstaller arduino array bitmap csv gis gogo ls matrix nw palette profiler py r rnd sound table time vid view2.5d"

      - name: Test 2D
        run: sbt -v -Dorg.nlogo.onLocal=false test

      - name: Test 3D
        run: sbt -v -Dorg.nlogo.onLocal=false -Dorg.nlogo.is3d=true test

      - name: Failure Debug Info
        if: ${{ failure() }}
        run: |
          pwd
          sudo apt-get -y install tree
          tree
